name: whatsapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  audio_waveforms: ^1.0.5
  audioplayers: ^6.0.0
  bloc: ^8.1.4
  camera: ^0.11.0+1
  cloud_firestore: ^4.17.3
  country_picker: ^2.0.25
  custom_pop_up_menu: ^1.2.4
  emoji_picker_flutter: ^1.6.4
  equatable: ^2.0.5
  file_picker: ^8.0.5
  firebase_auth: ^4.19.5
  firebase_core: ^2.31.0
  firebase_storage: ^11.7.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_keyboard_visibility: ^6.0.0
  flutter_screenutil: ^5.9.0
  flutter_sound: ^9.11.2
  image: ^4.2.0
  image_picker: ^1.1.1
  intl: ^0.19.0
  otp_text_field: ^1.1.3
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  photo_view: ^0.15.0
  pin_code_fields: ^8.0.1
  popup_menu: ^2.0.0
  rxdart: ^0.27.7
  shared_preferences: ^2.2.3
  story_view: ^0.16.5
  stream_chat: ^8.0.0
  video_player: ^2.8.7

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/img/
