// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx8HRvQ-BRJRAxjSx6dLgxtjPfx0_rfJs',
    appId: '1:766450133190:web:19800ad06e608192d10fc7',
    messagingSenderId: '766450133190',
    projectId: 'whatsapp-87bab',
    authDomain: 'whatsapp-87bab.firebaseapp.com',
    storageBucket: 'whatsapp-87bab.appspot.com',
    measurementId: 'G-YZZX7QVGCH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-zBJLNcrpGW6nHIDE-sVEKhukzmLbf_M',
    appId: '1:766450133190:android:0d6e5cdf4414e82ed10fc7',
    messagingSenderId: '766450133190',
    projectId: 'whatsapp-87bab',
    storageBucket: 'whatsapp-87bab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEnJnk5Y53Txe0hqIlUI9fg0q1OALG-XI',
    appId: '1:766450133190:ios:4f61119cc4bcc2f2d10fc7',
    messagingSenderId: '766450133190',
    projectId: 'whatsapp-87bab',
    storageBucket: 'whatsapp-87bab.appspot.com',
    iosBundleId: 'com.example.whatsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEnJnk5Y53Txe0hqIlUI9fg0q1OALG-XI',
    appId: '1:766450133190:ios:4f61119cc4bcc2f2d10fc7',
    messagingSenderId: '766450133190',
    projectId: 'whatsapp-87bab',
    storageBucket: 'whatsapp-87bab.appspot.com',
    iosBundleId: 'com.example.whatsapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDx8HRvQ-BRJRAxjSx6dLgxtjPfx0_rfJs',
    appId: '1:766450133190:web:70a9b1659c67c206d10fc7',
    messagingSenderId: '766450133190',
    projectId: 'whatsapp-87bab',
    authDomain: 'whatsapp-87bab.firebaseapp.com',
    storageBucket: 'whatsapp-87bab.appspot.com',
    measurementId: 'G-VFDW0KZJC0',
  );

}