// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZfVig8fIiKn9IdiMEzaSjcMd6E5I-xWA',
    appId: '1:349167961199:web:1578dd684c3f0afa0af99a',
    messagingSenderId: '349167961199',
    projectId: 'whatsapp-4c3bd',
    authDomain: 'whatsapp-4c3bd.firebaseapp.com',
    storageBucket: 'whatsapp-4c3bd.appspot.com',
    measurementId: 'G-MGLCYBNJR7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBR5X7_tfJWOgEP_0IoKG7EJ6xNfgnYULk',
    appId: '1:349167961199:android:27dc4e2118fb07920af99a',
    messagingSenderId: '349167961199',
    projectId: 'whatsapp-4c3bd',
    storageBucket: 'whatsapp-4c3bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvcw0rKSoZwENfFpRu2YnEtkx8mx3I3Cw',
    appId: '1:349167961199:ios:2f2d0e0218664ad50af99a',
    messagingSenderId: '349167961199',
    projectId: 'whatsapp-4c3bd',
    storageBucket: 'whatsapp-4c3bd.appspot.com',
    iosBundleId: 'com.example.whatsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvcw0rKSoZwENfFpRu2YnEtkx8mx3I3Cw',
    appId: '1:349167961199:ios:2f2d0e0218664ad50af99a',
    messagingSenderId: '349167961199',
    projectId: 'whatsapp-4c3bd',
    storageBucket: 'whatsapp-4c3bd.appspot.com',
    iosBundleId: 'com.example.whatsapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZfVig8fIiKn9IdiMEzaSjcMd6E5I-xWA',
    appId: '1:349167961199:web:6941b4565c5a49710af99a',
    messagingSenderId: '349167961199',
    projectId: 'whatsapp-4c3bd',
    authDomain: 'whatsapp-4c3bd.firebaseapp.com',
    storageBucket: 'whatsapp-4c3bd.appspot.com',
    measurementId: 'G-TMQLBMXSFX',
  );

}