// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDs4b6gwNgbZcMV1V2N4EV5OLHDdhRpqrw',
    appId: '1:881847864275:web:7c1cfb5d57f01d74dabd26',
    messagingSenderId: '881847864275',
    projectId: 'whatsapp-e9878',
    authDomain: 'whatsapp-e9878.firebaseapp.com',
    storageBucket: 'whatsapp-e9878.appspot.com',
    measurementId: 'G-FLJ519VF1E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGffILP-WPGi0KwmqQEEyVsP-Z9o4R2iU',
    appId: '1:881847864275:android:91a8b44644afc233dabd26',
    messagingSenderId: '881847864275',
    projectId: 'whatsapp-e9878',
    storageBucket: 'whatsapp-e9878.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWVRJEG5iWsgqpKlLU0_iQpZwkQt5nQRA',
    appId: '1:881847864275:ios:aabfddf0cfe261b0dabd26',
    messagingSenderId: '881847864275',
    projectId: 'whatsapp-e9878',
    storageBucket: 'whatsapp-e9878.appspot.com',
    iosBundleId: 'com.example.whatsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWVRJEG5iWsgqpKlLU0_iQpZwkQt5nQRA',
    appId: '1:881847864275:ios:aabfddf0cfe261b0dabd26',
    messagingSenderId: '881847864275',
    projectId: 'whatsapp-e9878',
    storageBucket: 'whatsapp-e9878.appspot.com',
    iosBundleId: 'com.example.whatsapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDs4b6gwNgbZcMV1V2N4EV5OLHDdhRpqrw',
    appId: '1:881847864275:web:522af769e768c84edabd26',
    messagingSenderId: '881847864275',
    projectId: 'whatsapp-e9878',
    authDomain: 'whatsapp-e9878.firebaseapp.com',
    storageBucket: 'whatsapp-e9878.appspot.com',
    measurementId: 'G-SKMNVPYD9S',
  );
}
